In [37]:
import torch

Create empty tensor

In [38]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.1928, 0.2330],
        [0.0695, 0.5199]])
tensor([[0.4508, 0.8161],
        [0.2779, 0.8260]])


In [39]:
z = x + y
print(z)

tensor([[0.6436, 1.0491],
        [0.3474, 1.3459]])


In [40]:
z = torch.add(x, y)
print(z)

tensor([[0.6436, 1.0491],
        [0.3474, 1.3459]])


In [41]:
y.add_(x)
print(y)

tensor([[0.6436, 1.0491],
        [0.3474, 1.3459]])


In [42]:
z = x / y
print(z)

tensor([[0.2996, 0.2221],
        [0.2001, 0.3863]])


In [43]:
z = torch.div(x, y)
print(z)

tensor([[0.2996, 0.2221],
        [0.2001, 0.3863]])


In [52]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7173, 0.7482, 0.2071],
        [0.3948, 0.3724, 0.6202],
        [0.4682, 0.5114, 0.8263],
        [0.5262, 0.7857, 0.5075],
        [0.2608, 0.8243, 0.6058]])


In [54]:
print(x[:, 0]) # all rows for 0 column
print(x[1, :]) # all columns for 1st raw

tensor([0.7173, 0.3948, 0.4682, 0.5262, 0.2608])
tensor([0.3948, 0.3724, 0.6202])


In [56]:
print(x[1, 1]) # print element in raw 1 column 1
print(x[1, 1].item()) # print element's value in raw 1 column 1

tensor(0.3724)
0.37241238355636597


Create new tensor

In [63]:
x = torch.rand(4, 4)
print(x)

tensor([[0.1130, 0.9065, 0.7619, 0.7639],
        [0.5591, 0.9500, 0.0840, 0.9703],
        [0.9447, 0.9371, 0.4749, 0.2788],
        [0.0023, 0.5946, 0.9686, 0.5486]])


# Resizing tensors

Reshaping tensor in vector of 16 elements (not a raw, not a column, cause 1D dimension):

In [59]:
y = x.view(16)
print(y)

tensor([0.9216, 0.9796, 0.0556, 0.7999, 0.3326, 0.4865, 0.9035, 0.4403, 0.1135,
        0.5351, 0.6349, 0.5035, 0.8146, 0.0679, 0.6084, 0.3264])


Reshaping in one column with 16 raws

In [66]:
y = x.view(-1, 16)
print(y)

tensor([[0.1130, 0.9065, 0.7619, 0.7639, 0.5591, 0.9500, 0.0840, 0.9703, 0.9447,
         0.9371, 0.4749, 0.2788, 0.0023, 0.5946, 0.9686, 0.5486]])


Differences between 2 previous examples are:
1) 1st tensor has 1D dimension (vector)
2) 2nd tensor has 2D dimension (matrix (1, 16))

In [67]:
y = x.view(-1, 8)
print(y)

tensor([[0.1130, 0.9065, 0.7619, 0.7639, 0.5591, 0.9500, 0.0840, 0.9703],
        [0.9447, 0.9371, 0.4749, 0.2788, 0.0023, 0.5946, 0.9686, 0.5486]])


In [69]:
y = x.view(-1, 4)
print(y)

tensor([[0.1130, 0.9065, 0.7619, 0.7639],
        [0.5591, 0.9500, 0.0840, 0.9703],
        [0.9447, 0.9371, 0.4749, 0.2788],
        [0.0023, 0.5946, 0.9686, 0.5486]])


In [70]:
y = x.view(-1, 2)
print(y)

tensor([[0.1130, 0.9065],
        [0.7619, 0.7639],
        [0.5591, 0.9500],
        [0.0840, 0.9703],
        [0.9447, 0.9371],
        [0.4749, 0.2788],
        [0.0023, 0.5946],
        [0.9686, 0.5486]])


In [71]:
print(y.size())

torch.Size([8, 2])
