In [1]:
import torch

Create empty tensor

In [23]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.2630, 0.6521],
        [0.8753, 0.8151]])
tensor([[0.1355, 0.0806],
        [0.7547, 0.5413]])


In [24]:
z = x + y
print(z)

tensor([[0.3985, 0.7327],
        [1.6301, 1.3564]])


In [25]:
z = torch.add(x, y)
print(z)

tensor([[0.3985, 0.7327],
        [1.6301, 1.3564]])


In [26]:
y.add_(x)
print(y)

tensor([[0.3985, 0.7327],
        [1.6301, 1.3564]])


In [31]:
z = x / y
print(z)

tensor([[0.6600, 0.8900],
        [0.5370, 0.6009]])


In [32]:
z = torch.div(x, y)
print(z)

tensor([[0.6600, 0.8900],
        [0.5370, 0.6009]])
